require:
  - standard

plugins:
  - rubocop-rails
  - standard-performance
  - standard-rails
  - rubocop-performance

inherit_gem:
  standard: config/base.yml
  standard-rails: config/base.yml
  standard-performance: config/base.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
